graphdriver/quota: Disable disk_quota tests if build tag is set
Avoid running the projectquota unit tests to avoid the follwing
errors:

	daemon/graphdriver/quota/projectquota_test.go:89:24: undefined: makeBackingFsDev
	daemon/graphdriver/quota/projectquota_test.go:97:21: undefined: hasQuotaSupport
	daemon/graphdriver/quota/projectquota_test.go:103:21: undefined: hasQuotaSupport

Signed-off-by: Robert Günzler <robertg@balena.io>